Fix error when migrating
NoMethodError: undefined method `auto_explain_threshold_in_seconds=' for
ActiveRecord::Base:Class
/g5-content-management-system/config/environment.rb:5:in `<top
(required)>'