Use rails from 4-1-stable branch
Fix has not been released yet.

1) StaticWebsite::Compiler::WebTemplate#view.compile when compile path
is present writes file to compile path Failure/Error:
subject.view.compile NoMethodError: undefined method `variant' for
nil:NilClass
     # ./lib/static_website/compiler/view.rb:27:in `block in
     # render_to_file' ./lib/static_website/compiler/view.rb:26:in
     # `open' ./lib/static_website/compiler/view.rb:26:in
     # `render_to_file' ./lib/static_website/compiler/view.rb:16:in
     # `compile'
     # ./spec/lib/static_website/compiler/web_template_spec.rb:53:in
     # `block (4 levels) in <top (required)>'